name: expense_flow
description: "Expense Flow - Track Smart. Spend Better."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Core & State Management ---
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # --- Local Database & Storage ---
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

  # --- UI & Styling ---
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  fl_chart: ^0.66.2

  # --- File, Sharing & Launchers ---
  excel: ^4.0.3
  file_picker: ^8.0.0
  share_plus: ^8.0.3
  url_launcher: ^6.2.5

  # --- Icons ---
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1

# --- Launcher Icons Config ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

# --- Flutter Assets & Configuration ---
flutter:
  uses-material-design: true

  assets:
    - assets/images/profile.PNG
    - assets/images/logo.png